{{- if eq .Values.gardener.seed.provider "hcloud" }}
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
provisioner: csi.hetzner.cloud
volumeBindingMode: {{ .Values.gardener.seed.spec.provider.providerConfig.volumeBindingMode }}
allowVolumeExpansion: true
{{- if .Values.gardener.seed.spec.provider.providerConfig.fsType }}
parameters:
  csi.storage.k8s.io/fstype: {{ .Values.gardener.seed.spec.provider.providerConfig.fsType }}
{{- end }}
{{- end }}
