{{- if eq .Values.gardener.seed.provider "hcloud" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.hetzner.cloud
volumeBindingMode: {{ .Values.gardener.seed.spec.provider.providerConfig.volumeBindingMode }}
allowVolumeExpansion: true
{{- if .Values.gardener.seed.spec.provider.providerConfig.fsType }}
parameters:
  fsType: {{ .Values.gardener.seed.spec.provider.providerConfig.fsType }}
{{- end }}
{{- end }}
