---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedresources.resources.gardener.cloud
spec:
  group: resources.gardener.cloud
  versions:
  - name: v1alpha1
    served: true
    storage: true
    additionalPrinterColumns:
    - name: Class
      type: string
      jsonPath: .spec.class
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: managedresources
    singular: managedresource
    kind: ManagedResource
    shortNames:
    - mr
