---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedresources.resources.gardener.cloud
spec:
  group: resources.gardener.cloud
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    plural: managedresources
    singular: managedresource
    kind: ManagedResource
    shortNames:
    - mr
  additionalPrinterColumns:
  - name: Class
    type: string
    JSONPath: .spec.class
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
