apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--hcloud
  labels:
    backup.gardener.cloud/provider: hcloud
    seed.gardener.cloud/provider: hcloud
    shoot.gardener.cloud/provider: hcloud
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--hcloud
type: Opaque
data:
  hcloudToken: base64token
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--hcloud
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
    spec:
      regions:
        - name: hel1
          zones:
          - name: hel1-dc2
      providerConfig:
        apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
        kind: CloudProfileConfig
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
    spec:
      settings:
        loadBalancerServices:
          annotations:
            load-balancer.hetzner.cloud/name: shoot--foobar--hcloud
            load-balancer.hetzner.cloud/location: hel1
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      cloud:
        hcloud:
          networks:
            pods: 10.250.0.0/19
      kubernetes:
        version: 1.13.4
      hibernation:
        enabled: false
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: control-plane
  namespace: shoot--foobar--hcloud
spec:
  type: hcloud
  region: hel1
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--hcloud
  providerConfig:
    apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
    kind: ControlPlaneConfig
    zone: hel1-dc2
    cloudControllerManager:
      featureGates:
        CustomResourceValidation: true
  infrastructureProviderStatus:
    apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    networks:
      floatingPool:
        id: vpc-1234
      subnets:
      - purpose: nodes
        id: subnetid
