---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--hcloud

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--hcloud
type: Opaque
data:
  hcloudToken: base64token

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--hcloud
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
    spec:
      regions:
      - name: hel1-dc2
      machineTypes:
        - name: cx11
      providerConfig:
        apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
        kind: CloudProfileConfig
        regions:
        - name: hel1-dc2
        machineImages:
          - name: ubuntu
            versions:
              - version: "20.04"
        machineTypes:
        - name: cx11

  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      kubernetes:
        version: 1.13.4
      region: hel1-dc2
      cloud:
        hcloud:
          test: foo
    status:
      lastOperation:
        state: Succeeded

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  name: infrastructure
  namespace: shoot--foobar--hcloud
spec:
  type: hcloud
  region: hel1-dc2
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--hcloud
  providerConfig:
    apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    floatingPoolName: MY-FLOATING-POOL
    # floatingPoolSubnetName: my-floating-pool-subnet-name
    networks:
    # router:
    #   id: 1234
      workers: 10.250.0.0/19
  sshPublicKey: AAAA
