// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	hcloud "github.com/23technologies/gardener-extension-provider-hcloud/pkg/apis/hcloud"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*hcloud.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(a.(*CloudProfileConfig), b.(*hcloud.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*hcloud.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerDaemonOptions)(nil), (*hcloud.DockerDaemonOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DockerDaemonOptions_To_hcloud_DockerDaemonOptions(a.(*DockerDaemonOptions), b.(*hcloud.DockerDaemonOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.DockerDaemonOptions)(nil), (*DockerDaemonOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(a.(*hcloud.DockerDaemonOptions), b.(*DockerDaemonOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*hcloud.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_hcloud_MachineImage(a.(*MachineImage), b.(*hcloud.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineImage_To_v1alpha1_MachineImage(a.(*hcloud.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*hcloud.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(a.(*MachineImageVersion), b.(*hcloud.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*hcloud.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*hcloud.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_hcloud_MachineImages(a.(*MachineImages), b.(*hcloud.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineImages_To_v1alpha1_MachineImages(a.(*hcloud.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineTypeOptions)(nil), (*hcloud.MachineTypeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(a.(*MachineTypeOptions), b.(*hcloud.MachineTypeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineTypeOptions)(nil), (*MachineTypeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(a.(*hcloud.MachineTypeOptions), b.(*MachineTypeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionSpec)(nil), (*hcloud.RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(a.(*RegionSpec), b.(*hcloud.RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.RegionSpec)(nil), (*RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(a.(*hcloud.RegionSpec), b.(*RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*hcloud.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(a.(*WorkerStatus), b.(*hcloud.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*hcloud.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(in *CloudProfileConfig, out *hcloud.CloudProfileConfig, s conversion.Scope) error {
	out.Regions = *(*[]hcloud.RegionSpec)(unsafe.Pointer(&in.Regions))
	out.MachineImages = *(*[]hcloud.MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.MachineTypeOptions = *(*[]hcloud.MachineTypeOptions)(unsafe.Pointer(&in.MachineTypeOptions))
	out.DockerDaemonOptions = (*hcloud.DockerDaemonOptions)(unsafe.Pointer(in.DockerDaemonOptions))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(in *CloudProfileConfig, out *hcloud.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(in, out, s)
}

func autoConvert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *hcloud.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.Regions = *(*[]RegionSpec)(unsafe.Pointer(&in.Regions))
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.MachineTypeOptions = *(*[]MachineTypeOptions)(unsafe.Pointer(&in.MachineTypeOptions))
	out.DockerDaemonOptions = (*DockerDaemonOptions)(unsafe.Pointer(in.DockerDaemonOptions))
	return nil
}

// Convert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *hcloud.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_DockerDaemonOptions_To_hcloud_DockerDaemonOptions(in *DockerDaemonOptions, out *hcloud.DockerDaemonOptions, s conversion.Scope) error {
	out.HTTPProxyConf = (*string)(unsafe.Pointer(in.HTTPProxyConf))
	out.InsecureRegistries = *(*[]string)(unsafe.Pointer(&in.InsecureRegistries))
	return nil
}

// Convert_v1alpha1_DockerDaemonOptions_To_hcloud_DockerDaemonOptions is an autogenerated conversion function.
func Convert_v1alpha1_DockerDaemonOptions_To_hcloud_DockerDaemonOptions(in *DockerDaemonOptions, out *hcloud.DockerDaemonOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_DockerDaemonOptions_To_hcloud_DockerDaemonOptions(in, out, s)
}

func autoConvert_hcloud_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(in *hcloud.DockerDaemonOptions, out *DockerDaemonOptions, s conversion.Scope) error {
	out.HTTPProxyConf = (*string)(unsafe.Pointer(in.HTTPProxyConf))
	out.InsecureRegistries = *(*[]string)(unsafe.Pointer(&in.InsecureRegistries))
	return nil
}

// Convert_hcloud_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions is an autogenerated conversion function.
func Convert_hcloud_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(in *hcloud.DockerDaemonOptions, out *DockerDaemonOptions, s conversion.Scope) error {
	return autoConvert_hcloud_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_hcloud_MachineImage(in *MachineImage, out *hcloud.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_MachineImage_To_hcloud_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_hcloud_MachineImage(in *MachineImage, out *hcloud.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_hcloud_MachineImage(in, out, s)
}

func autoConvert_hcloud_MachineImage_To_v1alpha1_MachineImage(in *hcloud.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_hcloud_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_hcloud_MachineImage_To_v1alpha1_MachineImage(in *hcloud.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_hcloud_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(in *MachineImageVersion, out *hcloud.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(in *MachineImageVersion, out *hcloud.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(in, out, s)
}

func autoConvert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *hcloud.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *hcloud.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_hcloud_MachineImages(in *MachineImages, out *hcloud.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]hcloud.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_hcloud_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_hcloud_MachineImages(in *MachineImages, out *hcloud.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_hcloud_MachineImages(in, out, s)
}

func autoConvert_hcloud_MachineImages_To_v1alpha1_MachineImages(in *hcloud.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_hcloud_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_hcloud_MachineImages_To_v1alpha1_MachineImages(in *hcloud.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_hcloud_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(in *MachineTypeOptions, out *hcloud.MachineTypeOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.ExtraConfig = *(*map[string]string)(unsafe.Pointer(&in.ExtraConfig))
	return nil
}

// Convert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions is an autogenerated conversion function.
func Convert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(in *MachineTypeOptions, out *hcloud.MachineTypeOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(in, out, s)
}

func autoConvert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in *hcloud.MachineTypeOptions, out *MachineTypeOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.ExtraConfig = *(*map[string]string)(unsafe.Pointer(&in.ExtraConfig))
	return nil
}

// Convert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions is an autogenerated conversion function.
func Convert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in *hcloud.MachineTypeOptions, out *MachineTypeOptions, s conversion.Scope) error {
	return autoConvert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in, out, s)
}

func autoConvert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(in *RegionSpec, out *hcloud.RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MachineImages = *(*[]hcloud.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_RegionSpec_To_hcloud_RegionSpec is an autogenerated conversion function.
func Convert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(in *RegionSpec, out *hcloud.RegionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(in, out, s)
}

func autoConvert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(in *hcloud.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_hcloud_RegionSpec_To_v1alpha1_RegionSpec is an autogenerated conversion function.
func Convert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(in *hcloud.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	return autoConvert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(in *WorkerStatus, out *hcloud.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]hcloud.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(in *WorkerStatus, out *hcloud.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(in, out, s)
}

func autoConvert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in *hcloud.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in *hcloud.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}
