//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	hcloud "github.com/23technologies/gardener-extension-provider-hcloud/pkg/apis/hcloud"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*hcloud.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_hcloud_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*hcloud.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*hcloud.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*hcloud.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(a.(*CloudProfileConfig), b.(*hcloud.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*hcloud.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*hcloud.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_hcloud_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*hcloud.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*hcloud.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*hcloud.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_hcloud_InfrastructureConfig(a.(*InfrastructureConfig), b.(*hcloud.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*hcloud.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfigNetworkIDs)(nil), (*hcloud.InfrastructureConfigNetworkIDs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfigNetworkIDs_To_hcloud_InfrastructureConfigNetworkIDs(a.(*InfrastructureConfigNetworkIDs), b.(*hcloud.InfrastructureConfigNetworkIDs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.InfrastructureConfigNetworkIDs)(nil), (*InfrastructureConfigNetworkIDs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(a.(*hcloud.InfrastructureConfigNetworkIDs), b.(*InfrastructureConfigNetworkIDs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*hcloud.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_hcloud_InfrastructureStatus(a.(*InfrastructureStatus), b.(*hcloud.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*hcloud.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*hcloud.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_hcloud_MachineImage(a.(*MachineImage), b.(*hcloud.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineImage_To_v1alpha1_MachineImage(a.(*hcloud.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*hcloud.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(a.(*MachineImageVersion), b.(*hcloud.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*hcloud.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*hcloud.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_hcloud_MachineImages(a.(*MachineImages), b.(*hcloud.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineImages_To_v1alpha1_MachineImages(a.(*hcloud.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineTypeOptions)(nil), (*hcloud.MachineTypeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(a.(*MachineTypeOptions), b.(*hcloud.MachineTypeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.MachineTypeOptions)(nil), (*MachineTypeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(a.(*hcloud.MachineTypeOptions), b.(*MachineTypeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Network)(nil), (*hcloud.Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Network_To_hcloud_Network(a.(*Network), b.(*hcloud.Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.Network)(nil), (*Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_Network_To_v1alpha1_Network(a.(*hcloud.Network), b.(*Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Networks)(nil), (*hcloud.Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Networks_To_hcloud_Networks(a.(*Networks), b.(*hcloud.Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.Networks)(nil), (*Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_Networks_To_v1alpha1_Networks(a.(*hcloud.Networks), b.(*Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionSpec)(nil), (*hcloud.RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(a.(*RegionSpec), b.(*hcloud.RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.RegionSpec)(nil), (*RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(a.(*hcloud.RegionSpec), b.(*RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerConfig)(nil), (*hcloud.WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerConfig_To_hcloud_WorkerConfig(a.(*WorkerConfig), b.(*hcloud.WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.WorkerConfig)(nil), (*WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_WorkerConfig_To_v1alpha1_WorkerConfig(a.(*hcloud.WorkerConfig), b.(*WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*hcloud.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(a.(*WorkerStatus), b.(*hcloud.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hcloud.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*hcloud.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_hcloud_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *hcloud.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_hcloud_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_hcloud_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *hcloud.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_hcloud_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_hcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *hcloud.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_hcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_hcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *hcloud.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_hcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(in *CloudProfileConfig, out *hcloud.CloudProfileConfig, s conversion.Scope) error {
	out.Regions = *(*[]hcloud.RegionSpec)(unsafe.Pointer(&in.Regions))
	out.MachineImages = *(*[]hcloud.MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.DefaultStorageFsType = in.DefaultStorageFsType
	out.MachineTypeOptions = *(*[]hcloud.MachineTypeOptions)(unsafe.Pointer(&in.MachineTypeOptions))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(in *CloudProfileConfig, out *hcloud.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_hcloud_CloudProfileConfig(in, out, s)
}

func autoConvert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *hcloud.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.Regions = *(*[]RegionSpec)(unsafe.Pointer(&in.Regions))
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.DefaultStorageFsType = in.DefaultStorageFsType
	out.MachineTypeOptions = *(*[]MachineTypeOptions)(unsafe.Pointer(&in.MachineTypeOptions))
	return nil
}

// Convert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *hcloud.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_hcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_hcloud_ControlPlaneConfig(in *ControlPlaneConfig, out *hcloud.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*hcloud.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_hcloud_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_hcloud_ControlPlaneConfig(in *ControlPlaneConfig, out *hcloud.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_hcloud_ControlPlaneConfig(in, out, s)
}

func autoConvert_hcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *hcloud.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_hcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_hcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *hcloud.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_hcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_hcloud_InfrastructureConfig(in *InfrastructureConfig, out *hcloud.InfrastructureConfig, s conversion.Scope) error {
	out.Networks = (*hcloud.Networks)(unsafe.Pointer(in.Networks))
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_hcloud_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_hcloud_InfrastructureConfig(in *InfrastructureConfig, out *hcloud.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_hcloud_InfrastructureConfig(in, out, s)
}

func autoConvert_hcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *hcloud.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	out.Networks = (*Networks)(unsafe.Pointer(in.Networks))
	return nil
}

// Convert_hcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_hcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *hcloud.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_hcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfigNetworkIDs_To_hcloud_InfrastructureConfigNetworkIDs(in *InfrastructureConfigNetworkIDs, out *hcloud.InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_v1alpha1_InfrastructureConfigNetworkIDs_To_hcloud_InfrastructureConfigNetworkIDs is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfigNetworkIDs_To_hcloud_InfrastructureConfigNetworkIDs(in *InfrastructureConfigNetworkIDs, out *hcloud.InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfigNetworkIDs_To_hcloud_InfrastructureConfigNetworkIDs(in, out, s)
}

func autoConvert_hcloud_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(in *hcloud.InfrastructureConfigNetworkIDs, out *InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_hcloud_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs is an autogenerated conversion function.
func Convert_hcloud_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(in *hcloud.InfrastructureConfigNetworkIDs, out *InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	return autoConvert_hcloud_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_hcloud_InfrastructureStatus(in *InfrastructureStatus, out *hcloud.InfrastructureStatus, s conversion.Scope) error {
	out.SSHFingerprint = in.SSHFingerprint
	out.PlacementGroupIDs = *(*map[string]string)(unsafe.Pointer(&in.PlacementGroupIDs))
	out.PlacementGroupID = in.PlacementGroupID
	out.NetworkIDs = (*hcloud.InfrastructureConfigNetworkIDs)(unsafe.Pointer(in.NetworkIDs))
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_hcloud_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_hcloud_InfrastructureStatus(in *InfrastructureStatus, out *hcloud.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_hcloud_InfrastructureStatus(in, out, s)
}

func autoConvert_hcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *hcloud.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	out.SSHFingerprint = in.SSHFingerprint
	out.PlacementGroupIDs = *(*map[string]string)(unsafe.Pointer(&in.PlacementGroupIDs))
	out.PlacementGroupID = in.PlacementGroupID
	out.NetworkIDs = (*InfrastructureConfigNetworkIDs)(unsafe.Pointer(in.NetworkIDs))
	return nil
}

// Convert_hcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_hcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *hcloud.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_hcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_hcloud_MachineImage(in *MachineImage, out *hcloud.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_MachineImage_To_hcloud_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_hcloud_MachineImage(in *MachineImage, out *hcloud.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_hcloud_MachineImage(in, out, s)
}

func autoConvert_hcloud_MachineImage_To_v1alpha1_MachineImage(in *hcloud.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_hcloud_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_hcloud_MachineImage_To_v1alpha1_MachineImage(in *hcloud.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_hcloud_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(in *MachineImageVersion, out *hcloud.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.ImageName = in.ImageName
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(in *MachineImageVersion, out *hcloud.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_hcloud_MachineImageVersion(in, out, s)
}

func autoConvert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *hcloud.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.ImageName = in.ImageName
	return nil
}

// Convert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *hcloud.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_hcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_hcloud_MachineImages(in *MachineImages, out *hcloud.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]hcloud.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_hcloud_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_hcloud_MachineImages(in *MachineImages, out *hcloud.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_hcloud_MachineImages(in, out, s)
}

func autoConvert_hcloud_MachineImages_To_v1alpha1_MachineImages(in *hcloud.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_hcloud_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_hcloud_MachineImages_To_v1alpha1_MachineImages(in *hcloud.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_hcloud_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(in *MachineTypeOptions, out *hcloud.MachineTypeOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.ExtraConfig = *(*map[string]string)(unsafe.Pointer(&in.ExtraConfig))
	return nil
}

// Convert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions is an autogenerated conversion function.
func Convert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(in *MachineTypeOptions, out *hcloud.MachineTypeOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTypeOptions_To_hcloud_MachineTypeOptions(in, out, s)
}

func autoConvert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in *hcloud.MachineTypeOptions, out *MachineTypeOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.ExtraConfig = *(*map[string]string)(unsafe.Pointer(&in.ExtraConfig))
	return nil
}

// Convert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions is an autogenerated conversion function.
func Convert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in *hcloud.MachineTypeOptions, out *MachineTypeOptions, s conversion.Scope) error {
	return autoConvert_hcloud_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in, out, s)
}

func autoConvert_v1alpha1_Network_To_hcloud_Network(in *Network, out *hcloud.Network, s conversion.Scope) error {
	out.Cidr = in.Cidr
	return nil
}

// Convert_v1alpha1_Network_To_hcloud_Network is an autogenerated conversion function.
func Convert_v1alpha1_Network_To_hcloud_Network(in *Network, out *hcloud.Network, s conversion.Scope) error {
	return autoConvert_v1alpha1_Network_To_hcloud_Network(in, out, s)
}

func autoConvert_hcloud_Network_To_v1alpha1_Network(in *hcloud.Network, out *Network, s conversion.Scope) error {
	out.Cidr = in.Cidr
	return nil
}

// Convert_hcloud_Network_To_v1alpha1_Network is an autogenerated conversion function.
func Convert_hcloud_Network_To_v1alpha1_Network(in *hcloud.Network, out *Network, s conversion.Scope) error {
	return autoConvert_hcloud_Network_To_v1alpha1_Network(in, out, s)
}

func autoConvert_v1alpha1_Networks_To_hcloud_Networks(in *Networks, out *hcloud.Networks, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_v1alpha1_Networks_To_hcloud_Networks is an autogenerated conversion function.
func Convert_v1alpha1_Networks_To_hcloud_Networks(in *Networks, out *hcloud.Networks, s conversion.Scope) error {
	return autoConvert_v1alpha1_Networks_To_hcloud_Networks(in, out, s)
}

func autoConvert_hcloud_Networks_To_v1alpha1_Networks(in *hcloud.Networks, out *Networks, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_hcloud_Networks_To_v1alpha1_Networks is an autogenerated conversion function.
func Convert_hcloud_Networks_To_v1alpha1_Networks(in *hcloud.Networks, out *Networks, s conversion.Scope) error {
	return autoConvert_hcloud_Networks_To_v1alpha1_Networks(in, out, s)
}

func autoConvert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(in *RegionSpec, out *hcloud.RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MachineImages = *(*[]hcloud.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_RegionSpec_To_hcloud_RegionSpec is an autogenerated conversion function.
func Convert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(in *RegionSpec, out *hcloud.RegionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionSpec_To_hcloud_RegionSpec(in, out, s)
}

func autoConvert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(in *hcloud.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_hcloud_RegionSpec_To_v1alpha1_RegionSpec is an autogenerated conversion function.
func Convert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(in *hcloud.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	return autoConvert_hcloud_RegionSpec_To_v1alpha1_RegionSpec(in, out, s)
}

func autoConvert_v1alpha1_WorkerConfig_To_hcloud_WorkerConfig(in *WorkerConfig, out *hcloud.WorkerConfig, s conversion.Scope) error {
	out.PlacementGroupType = in.PlacementGroupType
	return nil
}

// Convert_v1alpha1_WorkerConfig_To_hcloud_WorkerConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkerConfig_To_hcloud_WorkerConfig(in *WorkerConfig, out *hcloud.WorkerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerConfig_To_hcloud_WorkerConfig(in, out, s)
}

func autoConvert_hcloud_WorkerConfig_To_v1alpha1_WorkerConfig(in *hcloud.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	out.PlacementGroupType = in.PlacementGroupType
	return nil
}

// Convert_hcloud_WorkerConfig_To_v1alpha1_WorkerConfig is an autogenerated conversion function.
func Convert_hcloud_WorkerConfig_To_v1alpha1_WorkerConfig(in *hcloud.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	return autoConvert_hcloud_WorkerConfig_To_v1alpha1_WorkerConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(in *WorkerStatus, out *hcloud.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]hcloud.MachineImage)(unsafe.Pointer(&in.MachineImages))
	out.PlacementGroupIDs = *(*map[string]int64)(unsafe.Pointer(&in.PlacementGroupIDs))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(in *WorkerStatus, out *hcloud.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_hcloud_WorkerStatus(in, out, s)
}

func autoConvert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in *hcloud.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	out.PlacementGroupIDs = *(*map[string]int64)(unsafe.Pointer(&in.PlacementGroupIDs))
	return nil
}

// Convert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in *hcloud.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_hcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}
