apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: kubernetes
    role: cloud-controller-manager
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: cloud-controller-manager
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: cloud-controller-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/from-prometheus: allowed
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: vsphere-cloud-controller-manager
        image: {{ index .Values.images "vsphere-cloud-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/vsphere-cloud-controller-manager
        - --allocate-node-cidrs=true
        - --cloud-provider=vsphere
        - --cloud-config=/etc/kubernetes/cloudprovider/cloudprovider.conf
        - --cluster-cidr={{ .Values.podNetwork }}
        - --cluster-name={{ .Values.clusterName }}
        - --concurrent-service-syncs=10
        - --configure-cloud-routes=true
        {{- include "cloud-controller-manager.featureGates" . | trimSuffix "," | indent 8 }}
        - --kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        - --leader-elect=true
        - --secure-port=10258
        - --port=0
        - --authentication-kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        - --authorization-kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        - --tls-cert-file=/var/lib/cloud-controller-manager-server/cloud-controller-manager-server.crt
        - --tls-private-key-file=/var/lib/cloud-controller-manager-server/cloud-controller-manager-server.key
        - --tls-cipher-suites={{ include "kubernetes.tlsCipherSuites" . | replace "\n" "," | trimPrefix "," }}
        - --v=2
        env:
        - name: ENABLE_ALPHA_NSXT_LB
          value: "true"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 10258
          successThreshold: 1
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        ports:
        - containerPort: 10258
          name: metrics
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: cloud-controller-manager
          mountPath: /var/lib/cloud-controller-manager
        - name: cloud-controller-manager-server
          mountPath: /var/lib/cloud-controller-manager-server
        - name: cloud-provider-config
          mountPath: /etc/kubernetes/cloudprovider/cloudprovider.conf
          subPath: cloudprovider.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloud-controller-manager
        secret:
          secretName: cloud-controller-manager
      - name: cloud-controller-manager-server
        secret:
          secretName: cloud-controller-manager-server
      - name: cloud-provider-config
        configMap:
          name: cloud-provider-config
