machineClasses:
- name: class-1
  cluster: shoot--foobar--hcloud
  zone: hel1-dc2
  machineType: cx11
  architecture: amd64
  imageName: ubuntu-20.04
  sshFingerprint: "00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff"
  placementGroupID: ""
  networkName: test-namespace-workers
  floatingPoolName: MY-FLOATING-POOL
  credentialsSecretRef:
    name: cloudprovider
    namespace: shoot-namespace
  secret:
    hcloudToken: base64token
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
  tags:
    mcm.gardener.cloud/cluster: shoot--foobar--hcloud
    mcm.gardener.cloud/role: node
