{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    gardener.cloud/purpose: machineclass
type: Opaque
data:
  token: {{ $machineClass.secret.hcloudToken }}
  userData: {{ $machineClass.secret.userData | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
credentialsSecretRef:
  name: {{ $machineClass.credentialsSecretRef.name }}
  namespace: {{ $machineClass.credentialsSecretRef.namespace }}
providerSpec:
  cluster: {{ $machineClass.cluster }}
  zone: {{ $machineClass.zone }}
  serverType: {{ $machineClass.machineType }}
  architecture: {{ $machineClass.architecture }}
  imageName: {{ $machineClass.imageName }}
  sshFingerprint: {{ $machineClass.sshFingerprint }}
  placementGroupID: {{ $machineClass.placementGroupID | quote }}
  networkName: {{ $machineClass.networkName }}
{{- if $machineClass.floatingPoolName }}
  floatingPoolName: {{ $machineClass.floatingPoolName }}
{{- end }}
{{- if $machineClass.extraConfig }}
  extraConfig:
{{ toYaml $machineClass.extraConfig | indent 4 }}
{{- end }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
provider: hclouddriver//127.0.0.1:8080
{{- end }}
