images:
  machine-controller-manager: image-repository:image-tag

replicas: 0

podAnnotations: {}

podLabels: {}

providerName: provider-foo

namespace:
  uid: uuid-of-namespace

metricsPort: 10258
metricsPort2: 10259

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
