---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
provisioner: csi.hetzner.cloud
volumeBindingMode: {{ .Values.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.allowVolumeExpansion }}
parameters:
  fsType: {{ .Values.fsType }}
