apiVersion: v1
kind: Secret
metadata:
  name: csi-vsphere-config
  namespace: kube-system
type: Opaque
data:
{{- if .Values.topologyAware }}
  csi-vsphere.conf: {{ include "csi-vsphere-conf" . | b64enc }}
{{- end }}