replicas: 1
clusterName: shoot-foo-bar
kubernetesVersion: 1.7.5
podAnnotations: {}
podLabels: {}
podRegion: hel1
podNetworkIDs:
  workers: ""
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  hcloud-cloud-controller-manager: image-repository:image-tag
loadBalancer:
  disableIPv6: true
  disablePrivateIngress: true
disableNetworkAttachedCheck: true
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi
