replicas: 1
clusterName: shoot-foo-bar
kubernetesVersion: 1.7.5
podAnnotations: {}
podLabels: {}
podLocation: hel1
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  hcloud-cloud-controller-manager: image-repository:image-tag
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi
