//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	apis "github.com/23technologies/gardener-extension-provider-hcloud/pkg/hcloud/apis"
	hcloud "github.com/hetznercloud/hcloud-go/hcloud"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CPLoadBalancerClass)(nil), (*apis.CPLoadBalancerClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CPLoadBalancerClass_To_apis_CPLoadBalancerClass(a.(*CPLoadBalancerClass), b.(*apis.CPLoadBalancerClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.CPLoadBalancerClass)(nil), (*CPLoadBalancerClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_CPLoadBalancerClass_To_v1alpha1_CPLoadBalancerClass(a.(*apis.CPLoadBalancerClass), b.(*CPLoadBalancerClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*apis.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_apis_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*apis.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*apis.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*apis.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_apis_CloudProfileConfig(a.(*CloudProfileConfig), b.(*apis.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*apis.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*apis.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_apis_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*apis.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*apis.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerDaemonOptions)(nil), (*apis.DockerDaemonOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DockerDaemonOptions_To_apis_DockerDaemonOptions(a.(*DockerDaemonOptions), b.(*apis.DockerDaemonOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.DockerDaemonOptions)(nil), (*DockerDaemonOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(a.(*apis.DockerDaemonOptions), b.(*DockerDaemonOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*apis.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_apis_InfrastructureConfig(a.(*InfrastructureConfig), b.(*apis.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*apis.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfigNetwork)(nil), (*apis.InfrastructureConfigNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfigNetwork_To_apis_InfrastructureConfigNetwork(a.(*InfrastructureConfigNetwork), b.(*apis.InfrastructureConfigNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.InfrastructureConfigNetwork)(nil), (*InfrastructureConfigNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_InfrastructureConfigNetwork_To_v1alpha1_InfrastructureConfigNetwork(a.(*apis.InfrastructureConfigNetwork), b.(*InfrastructureConfigNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfigNetworkIDs)(nil), (*apis.InfrastructureConfigNetworkIDs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfigNetworkIDs_To_apis_InfrastructureConfigNetworkIDs(a.(*InfrastructureConfigNetworkIDs), b.(*apis.InfrastructureConfigNetworkIDs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.InfrastructureConfigNetworkIDs)(nil), (*InfrastructureConfigNetworkIDs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(a.(*apis.InfrastructureConfigNetworkIDs), b.(*InfrastructureConfigNetworkIDs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfigNetworks)(nil), (*apis.InfrastructureConfigNetworks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfigNetworks_To_apis_InfrastructureConfigNetworks(a.(*InfrastructureConfigNetworks), b.(*apis.InfrastructureConfigNetworks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.InfrastructureConfigNetworks)(nil), (*InfrastructureConfigNetworks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_InfrastructureConfigNetworks_To_v1alpha1_InfrastructureConfigNetworks(a.(*apis.InfrastructureConfigNetworks), b.(*InfrastructureConfigNetworks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*apis.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_apis_InfrastructureStatus(a.(*InfrastructureStatus), b.(*apis.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*apis.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*apis.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_apis_MachineImage(a.(*MachineImage), b.(*apis.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_MachineImage_To_v1alpha1_MachineImage(a.(*apis.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*apis.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_apis_MachineImageVersion(a.(*MachineImageVersion), b.(*apis.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*apis.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*apis.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_apis_MachineImages(a.(*MachineImages), b.(*apis.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_MachineImages_To_v1alpha1_MachineImages(a.(*apis.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineTypeOptions)(nil), (*apis.MachineTypeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineTypeOptions_To_apis_MachineTypeOptions(a.(*MachineTypeOptions), b.(*apis.MachineTypeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.MachineTypeOptions)(nil), (*MachineTypeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(a.(*apis.MachineTypeOptions), b.(*MachineTypeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionSpec)(nil), (*apis.RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionSpec_To_apis_RegionSpec(a.(*RegionSpec), b.(*apis.RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.RegionSpec)(nil), (*RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_RegionSpec_To_v1alpha1_RegionSpec(a.(*apis.RegionSpec), b.(*RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*apis.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_apis_WorkerStatus(a.(*WorkerStatus), b.(*apis.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apis.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apis_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*apis.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CPLoadBalancerClass_To_apis_CPLoadBalancerClass(in *CPLoadBalancerClass, out *apis.CPLoadBalancerClass, s conversion.Scope) error {
	out.Name = in.Name
	out.IPPoolName = (*string)(unsafe.Pointer(in.IPPoolName))
	out.TCPAppProfileName = (*string)(unsafe.Pointer(in.TCPAppProfileName))
	out.UDPAppProfileName = (*string)(unsafe.Pointer(in.UDPAppProfileName))
	return nil
}

// Convert_v1alpha1_CPLoadBalancerClass_To_apis_CPLoadBalancerClass is an autogenerated conversion function.
func Convert_v1alpha1_CPLoadBalancerClass_To_apis_CPLoadBalancerClass(in *CPLoadBalancerClass, out *apis.CPLoadBalancerClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_CPLoadBalancerClass_To_apis_CPLoadBalancerClass(in, out, s)
}

func autoConvert_apis_CPLoadBalancerClass_To_v1alpha1_CPLoadBalancerClass(in *apis.CPLoadBalancerClass, out *CPLoadBalancerClass, s conversion.Scope) error {
	out.Name = in.Name
	out.IPPoolName = (*string)(unsafe.Pointer(in.IPPoolName))
	out.TCPAppProfileName = (*string)(unsafe.Pointer(in.TCPAppProfileName))
	out.UDPAppProfileName = (*string)(unsafe.Pointer(in.UDPAppProfileName))
	return nil
}

// Convert_apis_CPLoadBalancerClass_To_v1alpha1_CPLoadBalancerClass is an autogenerated conversion function.
func Convert_apis_CPLoadBalancerClass_To_v1alpha1_CPLoadBalancerClass(in *apis.CPLoadBalancerClass, out *CPLoadBalancerClass, s conversion.Scope) error {
	return autoConvert_apis_CPLoadBalancerClass_To_v1alpha1_CPLoadBalancerClass(in, out, s)
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_apis_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *apis.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_apis_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_apis_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *apis.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_apis_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_apis_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *apis.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_apis_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_apis_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *apis.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_apis_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_apis_CloudProfileConfig(in *CloudProfileConfig, out *apis.CloudProfileConfig, s conversion.Scope) error {
	out.Regions = *(*[]apis.RegionSpec)(unsafe.Pointer(&in.Regions))
	out.MachineImages = *(*[]apis.MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.DefaultStorageFsType = in.DefaultStorageFsType
	out.MachineTypeOptions = *(*[]apis.MachineTypeOptions)(unsafe.Pointer(&in.MachineTypeOptions))
	out.DockerDaemonOptions = (*apis.DockerDaemonOptions)(unsafe.Pointer(in.DockerDaemonOptions))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_apis_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_apis_CloudProfileConfig(in *CloudProfileConfig, out *apis.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_apis_CloudProfileConfig(in, out, s)
}

func autoConvert_apis_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *apis.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.Regions = *(*[]RegionSpec)(unsafe.Pointer(&in.Regions))
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.DefaultStorageFsType = in.DefaultStorageFsType
	out.MachineTypeOptions = *(*[]MachineTypeOptions)(unsafe.Pointer(&in.MachineTypeOptions))
	out.DockerDaemonOptions = (*DockerDaemonOptions)(unsafe.Pointer(in.DockerDaemonOptions))
	return nil
}

// Convert_apis_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_apis_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *apis.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_apis_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_apis_ControlPlaneConfig(in *ControlPlaneConfig, out *apis.ControlPlaneConfig, s conversion.Scope) error {
	out.Zone = in.Zone
	out.CloudControllerManager = (*apis.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.LoadBalancerClasses = *(*[]apis.CPLoadBalancerClass)(unsafe.Pointer(&in.LoadBalancerClasses))
	out.LoadBalancerSize = (*string)(unsafe.Pointer(in.LoadBalancerSize))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_apis_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_apis_ControlPlaneConfig(in *ControlPlaneConfig, out *apis.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_apis_ControlPlaneConfig(in, out, s)
}

func autoConvert_apis_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *apis.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.Zone = in.Zone
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.LoadBalancerClasses = *(*[]CPLoadBalancerClass)(unsafe.Pointer(&in.LoadBalancerClasses))
	out.LoadBalancerSize = (*string)(unsafe.Pointer(in.LoadBalancerSize))
	return nil
}

// Convert_apis_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_apis_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *apis.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_apis_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_DockerDaemonOptions_To_apis_DockerDaemonOptions(in *DockerDaemonOptions, out *apis.DockerDaemonOptions, s conversion.Scope) error {
	out.HTTPProxyConf = (*string)(unsafe.Pointer(in.HTTPProxyConf))
	out.InsecureRegistries = *(*[]string)(unsafe.Pointer(&in.InsecureRegistries))
	return nil
}

// Convert_v1alpha1_DockerDaemonOptions_To_apis_DockerDaemonOptions is an autogenerated conversion function.
func Convert_v1alpha1_DockerDaemonOptions_To_apis_DockerDaemonOptions(in *DockerDaemonOptions, out *apis.DockerDaemonOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_DockerDaemonOptions_To_apis_DockerDaemonOptions(in, out, s)
}

func autoConvert_apis_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(in *apis.DockerDaemonOptions, out *DockerDaemonOptions, s conversion.Scope) error {
	out.HTTPProxyConf = (*string)(unsafe.Pointer(in.HTTPProxyConf))
	out.InsecureRegistries = *(*[]string)(unsafe.Pointer(&in.InsecureRegistries))
	return nil
}

// Convert_apis_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions is an autogenerated conversion function.
func Convert_apis_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(in *apis.DockerDaemonOptions, out *DockerDaemonOptions, s conversion.Scope) error {
	return autoConvert_apis_DockerDaemonOptions_To_v1alpha1_DockerDaemonOptions(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_apis_InfrastructureConfig(in *InfrastructureConfig, out *apis.InfrastructureConfig, s conversion.Scope) error {
	out.FloatingPoolName = in.FloatingPoolName
	out.Networks = (*apis.InfrastructureConfigNetworks)(unsafe.Pointer(in.Networks))
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_apis_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_apis_InfrastructureConfig(in *InfrastructureConfig, out *apis.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_apis_InfrastructureConfig(in, out, s)
}

func autoConvert_apis_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *apis.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	out.FloatingPoolName = in.FloatingPoolName
	out.Networks = (*InfrastructureConfigNetworks)(unsafe.Pointer(in.Networks))
	return nil
}

// Convert_apis_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_apis_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *apis.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_apis_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfigNetwork_To_apis_InfrastructureConfigNetwork(in *InfrastructureConfigNetwork, out *apis.InfrastructureConfigNetwork, s conversion.Scope) error {
	out.Cidr = in.Cidr
	out.Zone = hcloud.NetworkZone(in.Zone)
	return nil
}

// Convert_v1alpha1_InfrastructureConfigNetwork_To_apis_InfrastructureConfigNetwork is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfigNetwork_To_apis_InfrastructureConfigNetwork(in *InfrastructureConfigNetwork, out *apis.InfrastructureConfigNetwork, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfigNetwork_To_apis_InfrastructureConfigNetwork(in, out, s)
}

func autoConvert_apis_InfrastructureConfigNetwork_To_v1alpha1_InfrastructureConfigNetwork(in *apis.InfrastructureConfigNetwork, out *InfrastructureConfigNetwork, s conversion.Scope) error {
	out.Cidr = in.Cidr
	out.Zone = hcloud.NetworkZone(in.Zone)
	return nil
}

// Convert_apis_InfrastructureConfigNetwork_To_v1alpha1_InfrastructureConfigNetwork is an autogenerated conversion function.
func Convert_apis_InfrastructureConfigNetwork_To_v1alpha1_InfrastructureConfigNetwork(in *apis.InfrastructureConfigNetwork, out *InfrastructureConfigNetwork, s conversion.Scope) error {
	return autoConvert_apis_InfrastructureConfigNetwork_To_v1alpha1_InfrastructureConfigNetwork(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfigNetworkIDs_To_apis_InfrastructureConfigNetworkIDs(in *InfrastructureConfigNetworkIDs, out *apis.InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_v1alpha1_InfrastructureConfigNetworkIDs_To_apis_InfrastructureConfigNetworkIDs is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfigNetworkIDs_To_apis_InfrastructureConfigNetworkIDs(in *InfrastructureConfigNetworkIDs, out *apis.InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfigNetworkIDs_To_apis_InfrastructureConfigNetworkIDs(in, out, s)
}

func autoConvert_apis_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(in *apis.InfrastructureConfigNetworkIDs, out *InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_apis_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs is an autogenerated conversion function.
func Convert_apis_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(in *apis.InfrastructureConfigNetworkIDs, out *InfrastructureConfigNetworkIDs, s conversion.Scope) error {
	return autoConvert_apis_InfrastructureConfigNetworkIDs_To_v1alpha1_InfrastructureConfigNetworkIDs(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfigNetworks_To_apis_InfrastructureConfigNetworks(in *InfrastructureConfigNetworks, out *apis.InfrastructureConfigNetworks, s conversion.Scope) error {
	out.WorkersConfiguration = (*apis.InfrastructureConfigNetwork)(unsafe.Pointer(in.WorkersConfiguration))
	out.Workers = in.Workers
	return nil
}

// Convert_v1alpha1_InfrastructureConfigNetworks_To_apis_InfrastructureConfigNetworks is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfigNetworks_To_apis_InfrastructureConfigNetworks(in *InfrastructureConfigNetworks, out *apis.InfrastructureConfigNetworks, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfigNetworks_To_apis_InfrastructureConfigNetworks(in, out, s)
}

func autoConvert_apis_InfrastructureConfigNetworks_To_v1alpha1_InfrastructureConfigNetworks(in *apis.InfrastructureConfigNetworks, out *InfrastructureConfigNetworks, s conversion.Scope) error {
	out.WorkersConfiguration = (*InfrastructureConfigNetwork)(unsafe.Pointer(in.WorkersConfiguration))
	out.Workers = in.Workers
	return nil
}

// Convert_apis_InfrastructureConfigNetworks_To_v1alpha1_InfrastructureConfigNetworks is an autogenerated conversion function.
func Convert_apis_InfrastructureConfigNetworks_To_v1alpha1_InfrastructureConfigNetworks(in *apis.InfrastructureConfigNetworks, out *InfrastructureConfigNetworks, s conversion.Scope) error {
	return autoConvert_apis_InfrastructureConfigNetworks_To_v1alpha1_InfrastructureConfigNetworks(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_apis_InfrastructureStatus(in *InfrastructureStatus, out *apis.InfrastructureStatus, s conversion.Scope) error {
	out.SSHFingerprint = in.SSHFingerprint
	out.PlacementGroupID = in.PlacementGroupID
	out.FloatingPoolName = in.FloatingPoolName
	out.NetworkIDs = (*apis.InfrastructureConfigNetworkIDs)(unsafe.Pointer(in.NetworkIDs))
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_apis_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_apis_InfrastructureStatus(in *InfrastructureStatus, out *apis.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_apis_InfrastructureStatus(in, out, s)
}

func autoConvert_apis_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *apis.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	out.SSHFingerprint = in.SSHFingerprint
	out.PlacementGroupID = in.PlacementGroupID
	out.FloatingPoolName = in.FloatingPoolName
	out.NetworkIDs = (*InfrastructureConfigNetworkIDs)(unsafe.Pointer(in.NetworkIDs))
	return nil
}

// Convert_apis_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_apis_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *apis.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_apis_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_apis_MachineImage(in *MachineImage, out *apis.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_MachineImage_To_apis_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_apis_MachineImage(in *MachineImage, out *apis.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_apis_MachineImage(in, out, s)
}

func autoConvert_apis_MachineImage_To_v1alpha1_MachineImage(in *apis.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_apis_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_apis_MachineImage_To_v1alpha1_MachineImage(in *apis.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_apis_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_apis_MachineImageVersion(in *MachineImageVersion, out *apis.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.ImageName = in.ImageName
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_apis_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_apis_MachineImageVersion(in *MachineImageVersion, out *apis.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_apis_MachineImageVersion(in, out, s)
}

func autoConvert_apis_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *apis.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.ImageName = in.ImageName
	return nil
}

// Convert_apis_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_apis_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *apis.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_apis_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_apis_MachineImages(in *MachineImages, out *apis.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]apis.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_apis_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_apis_MachineImages(in *MachineImages, out *apis.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_apis_MachineImages(in, out, s)
}

func autoConvert_apis_MachineImages_To_v1alpha1_MachineImages(in *apis.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_apis_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_apis_MachineImages_To_v1alpha1_MachineImages(in *apis.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_apis_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_MachineTypeOptions_To_apis_MachineTypeOptions(in *MachineTypeOptions, out *apis.MachineTypeOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.ExtraConfig = *(*map[string]string)(unsafe.Pointer(&in.ExtraConfig))
	return nil
}

// Convert_v1alpha1_MachineTypeOptions_To_apis_MachineTypeOptions is an autogenerated conversion function.
func Convert_v1alpha1_MachineTypeOptions_To_apis_MachineTypeOptions(in *MachineTypeOptions, out *apis.MachineTypeOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTypeOptions_To_apis_MachineTypeOptions(in, out, s)
}

func autoConvert_apis_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in *apis.MachineTypeOptions, out *MachineTypeOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.ExtraConfig = *(*map[string]string)(unsafe.Pointer(&in.ExtraConfig))
	return nil
}

// Convert_apis_MachineTypeOptions_To_v1alpha1_MachineTypeOptions is an autogenerated conversion function.
func Convert_apis_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in *apis.MachineTypeOptions, out *MachineTypeOptions, s conversion.Scope) error {
	return autoConvert_apis_MachineTypeOptions_To_v1alpha1_MachineTypeOptions(in, out, s)
}

func autoConvert_v1alpha1_RegionSpec_To_apis_RegionSpec(in *RegionSpec, out *apis.RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MachineImages = *(*[]apis.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_RegionSpec_To_apis_RegionSpec is an autogenerated conversion function.
func Convert_v1alpha1_RegionSpec_To_apis_RegionSpec(in *RegionSpec, out *apis.RegionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionSpec_To_apis_RegionSpec(in, out, s)
}

func autoConvert_apis_RegionSpec_To_v1alpha1_RegionSpec(in *apis.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_apis_RegionSpec_To_v1alpha1_RegionSpec is an autogenerated conversion function.
func Convert_apis_RegionSpec_To_v1alpha1_RegionSpec(in *apis.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	return autoConvert_apis_RegionSpec_To_v1alpha1_RegionSpec(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_apis_WorkerStatus(in *WorkerStatus, out *apis.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]apis.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_apis_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_apis_WorkerStatus(in *WorkerStatus, out *apis.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_apis_WorkerStatus(in, out, s)
}

func autoConvert_apis_WorkerStatus_To_v1alpha1_WorkerStatus(in *apis.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_apis_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_apis_WorkerStatus_To_v1alpha1_WorkerStatus(in *apis.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_apis_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}
