apiVersion: v1
kind: Service
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: cloud-controller-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 10258
      protocol: TCP
  selector:
    app: kubernetes
    role: cloud-controller-manager