name: End-to-End test
on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: self-hosted
    name: "End-to-End test"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: install Dependencies
        run: sudo apt-get update && sudo apt-get install -y apache2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.0"
      - name: Setup Gardener kubeconfig
        run: |
          echo "${{ secrets.GARDENER_KUBECONFIG }}" > hack/ci/secrets/gardener-kubeconfig.yaml
      - name: e2e test
        env:
          AZURE_DNS_CLIENT_ID: ${{ secrets.AZURE_DNS_CLIENT_ID }}
          AZURE_DNS_CLIENT_SECRET: ${{ secrets.AZURE_DNS_CLIENT_SECRET }}
          AZURE_DNS_SUBSCRIPTION_ID: ${{ secrets.AZURE_DNS_SUBSCRIPTION_ID }}
          AZURE_DNS_TENANT_ID: ${{ secrets.AZURE_DNS_TENANT_ID }}
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        run: |
          bash hack/ci/work.sh
