name: go:release

on:
  push:
    tags: 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Update VERSION file
      run: |-
          echo "${{ github.ref_name }}" > VERSION
    - name: Create controller-registration.yaml
      run: |-
          vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh provider-hcloud charts/gardener-extension-provider-hcloud ${{ github.ref_name }} controller-registration.yaml \
          ControlPlane:hcloud Infrastructure:hcloud Worker:hcloud
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        body: |-
          # [gardener-extension-provider-hcloud] ${{ github.ref_name }}
        files: |-
            controller-registration.yaml
  go-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: gardener-extension-provider-hcloud
        - name: gardener-extension-admission-hcloud

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Update VERSION file
      run: |-
          echo "${{ github.ref_name }}" > VERSION
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish image
      uses: docker/build-push-action@v2
      with:
        target: ${{ matrix.name }}
        push: true
        tags: |
          ghcr.io/23technologies/${{ matrix.name }}:latest
          ghcr.io/23technologies/${{ matrix.name }}:${{ github.ref_name }}
