name: go:publish

on:
  release:
    types: [ released ]

jobs:
  go-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Get the Git tag name
      id: get-tag-name
      run: echo ::set-output name=tag-name::${GITHUB_REF/refs\/tags\/v/}
    - name: Update VERSION file
      run: |-
          echo "${{ steps.get-tag-name.outputs.tag-name }}" > VERSION
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/23technologies/gardener-extension-provider-hcloud:latest
          ghcr.io/23technologies/gardener-extension-provider-hcloud:${{ steps.get-tag-name.outputs.tag-name }}
